In [1]:
import numpy as np

x = [5,7,-2,2]
y = [4,5,12,0]

In [2]:
A =np.array([[1,2],[2,1]])
B =np.array([[1,5],[0,2]])

In [3]:
A+5*B

array([[ 6, 27],
       [ 2, 11]])

In [4]:
A * B

array([[ 1, 10],
       [ 0,  2]])

In [5]:
np.dot(A,B)

array([[ 1,  9],
       [ 2, 12]])

In [6]:
a = np.array([0, 1, 2])
np.dot(a,a)

5

In [9]:
a = np.array([[0],[1],[2]])

In [10]:
a.shape

(3, 1)

In [11]:
a.T.shape

(1, 3)

In [12]:
a = np.array([
 [0],
 [7]
])
b = np.array([
 [1,2],
 [0,6]
])
c = np.array([
 [2,2]
])

In [13]:
A = np.array([[3,4],[2,3]])

In [14]:
A.T

array([[3, 2],
       [4, 3]])

In [15]:
bar = np.linalg.inv(A)

In [16]:
bar

array([[ 3., -4.],
       [-2.,  3.]])

In [17]:
A.dot(bar)

array([[ 1.,  0.],
       [ 0.,  1.]])

In [18]:
np.linalg.matrix_rank(A)

2

In [19]:
B=np.array([[1,0],[0,0]])
np.linalg.inv(B)

LinAlgError: Singular matrix

In [20]:
np.linalg.matrix_rank(B)

1

In [21]:
b=np.array([1,2])

In [23]:
x = np.linalg.solve(A,b)

In [24]:
A.dot(x)

array([ 1.,  2.])

In [25]:
b

array([1, 2])

In [35]:
A = np.array([[2,1,1],[-5,-3,0],[1,1,-1], [0,5,-1]])
b = np.array([-1,1,2,1])

In [37]:
np.linalg.matrix_rank(A)

3

In [38]:
A

array([[ 2,  1,  1],
       [-5, -3,  0],
       [ 1,  1, -1],
       [ 0,  5, -1]])

In [36]:
x = np.linalg.solve(A,b)

LinAlgError: Last 2 dimensions of the array must be square

In [29]:
A.dot(x)

array([-1.,  1.,  2.])

In [30]:
np.linalg.matrix_rank(A)

3

In [34]:
np.linalg.inv(A).dot(b)

array([-5.,  8.,  1.])

In [33]:
x

array([-5.,  8.,  1.])