In [2]:
import numpy as np

In [3]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [4]:
a1.ndim

1

In [5]:
a1.shape

(3,)

In [6]:
a2 = np.array([[1,2,3],[3,4,5]])
a2
a2.shape

(2, 3)

In [7]:
a2.ndim

2

In [8]:
a2.dtype

dtype('int32')

In [9]:
a1.dtype

dtype('int32')

In [10]:
a4 = np.array([ ['f','l','a','k','e'],['s','n','a','k','e'],['a','w','a','k','e'] ])
a4.shape

(3, 5)

In [11]:
a4.dtype

dtype('<U1')

In [12]:
x=np.array(11)
x.shape

()

In [13]:
x

array(11)

In [15]:
foo = np.array([[1],[2],[3],[4]])

In [17]:
foo.shape

(4, 1)

In [18]:
a = np.arange(12)

In [19]:
a.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [20]:
A = np.array( [[1,1], [0,1]] )
B = np.array( [[2,0], [3,4]] )

In [21]:
A * B

array([[2, 0],
       [0, 4]])

In [22]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [26]:
a = np.array([11,22])
b = np.array([18,7,6])
c = np.array([1,3,5])
d = np.concatenate((a,b,c))

In [27]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

In [28]:
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [29]:
np.concatenate((a, b), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [30]:
a = np.reshape(np.arange(12),(4,3))
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [31]:
a[0,0]

0

In [32]:
a[3,0]

9

In [34]:
a[3,2]

11

In [35]:
a[1:3,0]

array([3, 6])

In [36]:
a[:,1]

array([ 1,  4,  7, 10])

In [38]:
a[0:4:2,:]

array([[0, 1, 2],
       [6, 7, 8]])

In [39]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [42]:
a = np.array(np.arange(1,37))

In [43]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36])

In [45]:
b = np.reshape(a, (6,6))

In [46]:
b[:,1]

array([ 2,  8, 14, 20, 26, 32])

In [49]:
b[0:2,4:6]

array([[ 5,  6],
       [11, 12]])

In [50]:
b[5,4:6]

array([35, 36])

In [54]:
b[2::2, ::2]

array([[13, 15, 17],
       [25, 27, 29]])

In [55]:
a = np.reshape(np.arange(12),(4,3))

In [56]:
a>8

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [ True,  True,  True]], dtype=bool)

In [57]:
a[a>8]

array([ 9, 10, 11])

In [58]:
a[a>8]=0
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 0, 0]])

In [59]:
myarray = np.array([1,2,3])
myarray * 10

array([10, 20, 30])

In [60]:
a = np.array([[1], [2], [3], [4]])
b = np.array([10, 20, 30])
a + b

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33],
       [14, 24, 34]])

In [61]:
np.array([[1,2,3],[4,5,6]]) + np.array([[1,2],[8,10],[3,10]]) 

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [62]:
dist_to_origin = [0, 1498, 1063, 1968, 1498, 1758, 
1469, 1472, 2230, 2391]

In [64]:
dist = np.array(dist_to_origin)

In [65]:
dist_T = dist[:, np.newaxis]

In [66]:
dist_T

array([[   0],
       [1498],
       [1063],
       [1968],
       [1498],
       [1758],
       [1469],
       [1472],
       [2230],
       [2391]])

In [67]:
dist_matrix = np.abs(dist - dist_T)

In [68]:
dist_matrix

array([[   0, 1498, 1063, 1968, 1498, 1758, 1469, 1472, 2230, 2391],
       [1498,    0,  435,  470,    0,  260,   29,   26,  732,  893],
       [1063,  435,    0,  905,  435,  695,  406,  409, 1167, 1328],
       [1968,  470,  905,    0,  470,  210,  499,  496,  262,  423],
       [1498,    0,  435,  470,    0,  260,   29,   26,  732,  893],
       [1758,  260,  695,  210,  260,    0,  289,  286,  472,  633],
       [1469,   29,  406,  499,   29,  289,    0,    3,  761,  922],
       [1472,   26,  409,  496,   26,  286,    3,    0,  758,  919],
       [2230,  732, 1167,  262,  732,  472,  761,  758,    0,  161],
       [2391,  893, 1328,  423,  893,  633,  922,  919,  161,    0]])

In [24]:
d

array([11, 22, 18,  7,  6,  1,  3,  5])